### ISSUE TITLE
Homepage silhouette logo graphic

### ISSUE THREAD

**Issue by jackturner** [Vidvox/isf.video#10]
Make a collage-style graphic similar to the placeholder graphic from the HAP site we're currently using…
![image](https://user-images.githubusercontent.com/15309/53823139-25bacf00-3f3f-11e9-8f7b-cb390b08019c.png)

**Comment by aarontw** [comment]
@jackturner LMK!
![isf_exp_a](https://user-images.githubusercontent.com/1452630/53971081-23d14700-40ca-11e9-94ff-a800e4b2d1b4.png)
![isf_exp_b](https://user-images.githubusercontent.com/1452630/53971082-23d14700-40ca-11e9-9bd6-585ba80aca8e.png)

**Comment by dlublin** [comment]
Hey atw, if you make a version of that where each 'face' is a different solid color, I could make a shader that chroma-masks each and replaces it with a different video stream :0

**Comment by aarontw** [comment]
@dlublin PNG + SVG w/ RGB attached:
![isf_exp_rgb](https://user-images.githubusercontent.com/1452630/53971466-f769fa80-40ca-11e9-8f53-49fd9aba96ac.png)

**Comment by jackturner** [comment]
DO IT DAVID!

**Comment by jackturner** [comment]
@aarontw I love those two you made. I'll throw one of them in as a placeholder until we make a final decision or do some shader/video nonsense.
