### ISSUE TITLE
New W I D E graphic for homepage

### ISSUE THREAD

**Issue by jackturner** [Vidvox/isf.video#11]
We're currently just using the one from the HAP site…
![image](https://user-images.githubusercontent.com/15309/53823382-ab3e7f00-3f3f-11e9-98db-ded59461d703.png)

**Comment by aarontw** [comment]
@jackturner 

I am digging Silvia Fabiani's stuff for this, here's a still I found here:
https://vdmx.vidvox.net/blog/isf-from-silvia-fabiani

https://static1.squarespace.com/static/50169cf884ae68067baa7365/t/5b229534758d464729527224/1528994100543/?format=2500w

And also like this a lot:
https://www.instagram.com/p/BsF-r4JiNpO/?utm_source=ig_web_button_share_sheet

Wondering, would it be cool to do a bg video from ISF/shader like that in the div, with a fallback static image?

**Comment by dlublin** [comment]
"Wondering, would it be cool to do a bg video from ISF/shader like that in the div, with a fallback static image?"  – overall I like this idea, the one 'con' I have for this (or any frame grab of a video stream itself) is that loses the sense that this is something being projected / used in a larger project – that these shaders are meant to be combined in interesting ways more so than standalone compositions.

**Comment by jackturner** [comment]
A photo of something projected like this stuff seems ideal: https://www.silviafabiani.com/dedoublement

I think a shader, or video, or that awesome blue swirl that @aarontw pointed out would all catch your eye really well but wouldn't contextualize the technology in the way @dlublin is saying. Also, having one shader on the page is probably enough?

**Comment by aarontw** [comment]
Here are a few that include dancers w/ projection—does this go too far in showing actual people vs just the projection?

![32857607_1438575142915290_778166886268403712_o-1](https://user-images.githubusercontent.com/1452630/54041754-81cb6080-4196-11e9-8aaf-11eabb489dcf.jpg)
<img width="1440" alt="a963f7_8920acf8cfe3497a94e38aa55ff38d45_mv2_d_2880_1800_s_2" src="https://user-images.githubusercontent.com/1452630/54041755-81cb6080-4196-11e9-9efb-96306d55d982.png">
![ezgif-2-c1ec68107920](https://user-images.githubusercontent.com/1452630/54041757-81cb6080-4196-11e9-8489-b2d2e4e2cb8b.png)
![ezgif-2-cf78b405124a](https://user-images.githubusercontent.com/1452630/54041758-81cb6080-4196-11e9-8f19-f2690fa36216.png)
![ezgif-2-dc5690bc6a48](https://user-images.githubusercontent.com/1452630/54041759-81cb6080-4196-11e9-9677-e8a20468f873.png)

**Comment by dlublin** [comment]
Personally I love the blue one with the spiral from that set.

**Comment by jackturner** [comment]
The blue one is gorgeous and shows really unique use of ISF. Also, it would look amazing with a parallax effect so that most of what's visible is the ceiling and the people are only really in frame once you've scrolled down a bit. Also, I assume we can shift the blue hue it whatever direction (toxic green, perhaps @aarontw ?) we want.

The only problem I see is that it has a certain ultra-rich dubai/vegas vibe. At least when seen in isolation on something that's kinda like a product page. The more creative-exploration vibe of the other photos could be thing to represent the ISF brand. (personally i like the third one, so dynamic and so easy to tint) Just a consideration, the blue one is still cool and I'm going to drop it into the site along w/ the parallax effect I mentioned. That said, let us know if you want to try another photo.

**Comment by jackturner** [comment]
Actually the parallax is a bit wack with this image because then you end up with only seeing the pool when you scroll down…
![2019-03-12 17 26 22](https://user-images.githubusercontent.com/15309/54237350-1d890380-44ec-11e9-8dfa-9afb61085c2f.gif)

So I'm killing the parallax, for now.

**Comment by jackturner** [comment]
I think that what makes a good parallax image is actually some dead space at the top that it's ok to crop out when they scroll down. That actually makes that image w/ the dancer on white perfect. I'm down to try that.

**Comment by jackturner** [comment]
@dlublin suggested adding a caption to the image. Doing that…

**Comment by aarontw** [comment]
@jackturner this looks great!

Image is from https://www.sensoimmersive.com/en/category/press-en/ (May 22 entry):
https://www.sensoimmersive.com/wp-content/uploads/2018/05/Plaza-Twitter.jpg

**Comment by dlublin** [comment]
ATW, just wanted to make sure we captioned that correctly and I get proper permissions, curious how you ended up finding that pic? Was it through Silvia's page?

**Comment by aarontw** [comment]
Hmm now I checked again and am unsure of its provenance. I found it via Google image search with her name as a term in quotes—however, I think this is not her actual work:

site:https://www.sensoimmersive.com/ "Silvia Fabiani" — there are no results w/ her name in quotes, I missed that somehow, and can't be sure this is actually her work…

DOH.

**Comment by jackturner** [comment]
…still you get points for using "provenance" in a sentence =]

**Comment by aarontw** [comment]
![D4nCe_prOj3c710gn_A](https://user-images.githubusercontent.com/1452630/54716646-901d6300-4b2c-11e9-8b71-8c1fc148e1f4.jpg)

@jackturner something purple dayglo?

**Comment by jackturner** [comment]
That is intense and a fucking love it. I'll try it out on the page, w/ and w/o parallax and post a link here.

**Comment by aarontw** [comment]
![D4nCe_prOj3c710gn_D](https://user-images.githubusercontent.com/1452630/54716818-08842400-4b2d-11e9-868d-f8c5c4fe9894.jpg)

Haha cool! Here's a bluer version, maybe a little less nuts

**Comment by aarontw** [comment]
Basically working w/ the cooler range of inverse colors to our ectocooler green
![image](https://user-images.githubusercontent.com/1452630/54716898-43865780-4b2d-11e9-94ae-388cf9b5eb38.png)

**Comment by jackturner** [comment]
Hooke me up w/ a png (or other lossless) version of that last one?

**Comment by aarontw** [comment]
![D4nCe_prOj3c710gn_D](https://user-images.githubusercontent.com/1452630/54717518-b6440280-4b2e-11e9-8921-c26d5228c09a.png)
This one here?

**Comment by jackturner** [comment]
I currently have parallax rigged up, but it only works on wide desktop browsers:
https://isf.video/

@aarontw, @dlublin what do you think?
