### ISSUE TITLE
New layout for Examples page

### ISSUE THREAD

**Issue by jackturner** [Vidvox/isf.video#12]
What was once the Showcase is now Examples. This necessitates a new layout with the following qualities…

- items are 50% width _(until they go full-width in small browsers)_
- there is room for some text explaining what the project is
- on showcase the links to the tools and to the project are separate calls to action (circles below). in the new layout the links should be in the description text

![screen shot 2019-03-05 at 12 16 48 pm](https://user-images.githubusercontent.com/15309/53823874-a0381e80-3f40-11e9-9c05-39eaa90ae12c.png)

Am I leaving anything out @aarontw? Feel free to post designs here.

**Comment by aarontw** [comment]
@jackturner does this handle the job? To get a bit closer to the mobile UX, I moved those title strips above the image vs below. 

![examples 2x2 layout](https://user-images.githubusercontent.com/1452630/53970217-35b1ea80-40c8-11e9-88ca-d655b6a2c989.png)

**Comment by aarontw** [comment]
This is the basic interaction state I had in mind for the hover:
https://theintercept.com/

**Cathode green** overlay in lieu of purple here
![image](https://user-images.githubusercontent.com/1452630/53970448-c12b7b80-40c8-11e9-804b-350e51e44167.png)

**Comment by jackturner** [comment]
First off, love the toxic green hover state. But the whole thing should only be a hover state if the whole thing is clickable. But if the whole thing is a link, then we can't have links _within_ the body copy. 🤔 So maybe we could do it, but if there are two links in an example we shouldn't be able to make the "whole thing" a link. So maybe we just do the toxic green for the title of example and the image when you over over either of those two?

**Comment by jackturner** [comment]
@aarontw As I look at this layout I see a problem:

The site currently has a max-width of 1400px, so it's the full width of the browser for most people. Only people w/ windows bigger than that see any of the black background behind the body of the site. But the first column of examples has content extending off into that black background…
![image](https://user-images.githubusercontent.com/15309/54077896-026c8880-428d-11e9-840f-b05aca866525.png)

I'm just gonna work around that and try to keep the general feeling & white-space as your design but w/ all the content moved inside the body.

**Comment by aarontw** [comment]
This is looking solid @jackturner — one request, would it be possible to extend the black title bg divs to the width of the gray body wrapper?

![image](https://user-images.githubusercontent.com/1452630/54313981-d7e23e80-45b0-11e9-8d71-1227f02c850d.png)

and then aligning the text to be flush with the photos
![image](https://user-images.githubusercontent.com/1452630/54313971-d0229a00-45b0-11e9-831e-3b9692a315b9.png)
