### ISSUE TITLE
Tweak the layout of the header items

### ISSUE THREAD

**Issue by jackturner** [Vidvox/isf.video#13]
The alignment of the two-row nav w/ the logo is off. The size of the ISF logo-text is also off…

@aarontw is going give me an improved version.

**Comment by aarontw** [comment]
Hey @jackturner — here's where I am landing w/r/t the header item placement, feels pretty much visually resolved from my POV:

![image](https://user-images.githubusercontent.com/1452630/53967451-43b13c80-40c3-11e9-8846-86d0fc638713.png)

Let me know what you think—does this feel aligned to you?

**Comment by aarontw** [comment]
@jackturner and w/out guides

![isf_header_alignment](https://user-images.githubusercontent.com/1452630/53967646-97238a80-40c3-11e9-8ecc-613d586c021a.png)

**Comment by aarontw** [comment]
The only thing I am seeing is that the `EDITOR   DOCS`  nav feels just slightly too high, it maybe that there is a pixel or 2 padding/margin to fiddle with to bring that closer to the main nav items below it, though I wouldn't lower those, if that makes sense.

**Comment by jackturner** [comment]
Thanks @aarontw, I'll make these changes right away
