### ISSUE TITLE
Glyphs for the text blocks on homepage

### ISSUE THREAD

**Issue by jackturner** [Vidvox/isf.video#8]
For instance, for those four blocks on the homepage

This is work for atw

**Comment by jackturner** [comment]
@aarontw, this is the current text for this section…

> Make Modules, Not Engines – The ISF Specification is designed to promote creation of small re-usable shader code with the intention of using them as pieces of larger compositions within different host software as generators, effects and transitions with custom parameters for control. ISF includes features like multi-pass shaders with persistent buffers making it possible to create complex compound compositions and filters within a single portable document.

> Write Once, Use Widely, Remix Freely – Usage of ISF is already supported natively or by 3rd party plugins in nearly a dozen of the most popular media servers, real-time video applications, and creative coding environments, making it easy to switch tools without having to rewrite your shaders. Shaders can be created, modified and remixed using any standard text editor, or with the free ISF Editor tools.

> Standard Shaders – Along with the ISF specification itself, there are hundreds of 100% free and totally open source shaders available as part of this project. This includes a collection of over 200 standard color adjustment, blurs, distortion, geometry and stylizing shaders to get started with out of the box, or use as starting points for your own creations.

Pretty heady concepts for glyphs.

**Comment by jackturner** [comment]
Homepage w/ the three-block layout:
https://isf.video/

Awaiting glyphs

**Comment by aarontw** [comment]
@jackturner sharing progress…

![image](https://user-images.githubusercontent.com/1452630/54314691-b2eecb00-45b2-11e9-806a-fc14e2999fd1.png)

Need to refine these a bit methinks…

**Comment by jackturner** [comment]
It would be too busy on the homepage (especially if we do a video/shader version of the big ISF logo) but don't these feel like they _want_ to be animated?

**Comment by jackturner** [comment]
The remix one could have those those dissipating energy lines bouncing off of other cubes

**Comment by aarontw** [comment]
![icons-2](https://user-images.githubusercontent.com/1452630/54719510-7e8b8980-4b33-11e9-8bb5-2c1050591dd1.png)

Updated icons—LMK!

**Comment by dlublin** [comment]
I dig, but for the left-most one, maybe the boxes could be connected by a couple of lines? Maybe the smaller cubes each have one going to the big cube?

**Comment by jackturner** [comment]
Yo @aarontw, hook me up with some assets.

**Comment by aarontw** [comment]
hey @jackturner thx for your patience! here are SVGs and PNGs at 4x:
https://www.dropbox.com/sh/2lod8rveg1lo4lr/AAAJ33QUfi21UnkVSXVUSckea?dl=0
